using System.Text;

namespace Chimpiler.Dacpac;

public sealed class PostgreSqlSqlGenerator
{
    public string GenerateScript(DeploymentPlan plan)
    {
        var builder = new StringBuilder();
        builder.AppendLine("-- Generated by Chimpiler dacpac apply.");
        builder.AppendLine("-- Review before execution. No SQL Server deployment script was copied or translated.");
        builder.AppendLine("BEGIN;");
        builder.AppendLine("SELECT pg_advisory_xact_lock(hashtextextended('chimpiler:dacpac:' || current_database(), 0));");

        foreach (var operation in plan.Operations)
        {
            builder.AppendLine();
            builder.AppendLine($"-- {operation.Description}");
            builder.AppendLine(Terminate(operation.Sql));
        }

        builder.AppendLine();
        builder.AppendLine("COMMIT;");
        return builder.ToString();
    }

    public string CreateTable(DatabaseTable table)
    {
        var columns = table.Columns.Select(ColumnDefinition);
        return $"CREATE TABLE {Qualified(table.Schema, table.Name)} (\n    {string.Join(",\n    ", columns)}\n)";
    }

    public string AddColumn(DatabaseTable table, DatabaseColumn column) =>
        $"ALTER TABLE {Qualified(table.Schema, table.Name)} ADD COLUMN {ColumnDefinition(column)}";

    public string AddPrimaryKey(DatabaseTable table, DatabaseKey key) =>
        $"ALTER TABLE {Qualified(table.Schema, table.Name)} ADD CONSTRAINT {Quote(key.Name)} PRIMARY KEY ({ColumnList(key.Columns)})";

    public string AddUniqueConstraint(DatabaseTable table, DatabaseKey key) =>
        $"ALTER TABLE {Qualified(table.Schema, table.Name)} ADD CONSTRAINT {Quote(key.Name)} UNIQUE ({ColumnList(key.Columns)})";

    public string AddForeignKey(DatabaseTable table, DatabaseForeignKey foreignKey) =>
        $"ALTER TABLE {Qualified(table.Schema, table.Name)} ADD CONSTRAINT {Quote(foreignKey.Name)} " +
        $"FOREIGN KEY ({ColumnList(foreignKey.Columns)}) REFERENCES {Qualified(foreignKey.ReferencedSchema, foreignKey.ReferencedTable)} " +
        $"({ColumnList(foreignKey.ReferencedColumns)}) ON DELETE {Action(foreignKey.OnDelete)} ON UPDATE {Action(foreignKey.OnUpdate)}";

    public string CreateIndex(DatabaseTable table, DatabaseIndex index)
    {
        var unique = index.IsUnique ? "UNIQUE " : string.Empty;
        var columns = string.Join(", ", index.Columns.Select(column =>
            $"{Quote(column.Name)}{(column.Ascending ? string.Empty : " DESC")}"));
        var include = index.IncludedColumns.Count == 0
            ? string.Empty
            : $" INCLUDE ({ColumnList(index.IncludedColumns)})";
        return $"CREATE {unique}INDEX {Quote(index.Name)} ON {Qualified(table.Schema, table.Name)} ({columns}){include}";
    }

    public string ColumnDefinition(DatabaseColumn column)
    {
        var builder = new StringBuilder();
        builder.Append(Quote(column.Name)).Append(' ').Append(column.StoreType);

        if (column.Identity is not null)
        {
            builder.Append(" GENERATED BY DEFAULT AS IDENTITY");
            if (column.Identity.Seed != 1 || column.Identity.Increment != 1)
            {
                builder.Append(" (START WITH ")
                    .Append(column.Identity.Seed)
                    .Append(" INCREMENT BY ")
                    .Append(column.Identity.Increment)
                    .Append(')');
            }
        }

        if (column.Default is not null)
        {
            builder.Append(" DEFAULT ").Append(column.Default.Sql);
        }

        builder.Append(column.IsNullable ? " NULL" : " NOT NULL");
        return builder.ToString();
    }

    public static string Quote(string identifier) => $"\"{identifier.Replace("\"", "\"\"", StringComparison.Ordinal)}\"";

    public static string Qualified(string schema, string name) => $"{Quote(schema)}.{Quote(name)}";

    public static string ColumnList(IEnumerable<string> columns) => string.Join(", ", columns.Select(Quote));

    private static string Action(ReferentialAction action) => action switch
    {
        ReferentialAction.NoAction => "NO ACTION",
        ReferentialAction.Cascade => "CASCADE",
        ReferentialAction.SetNull => "SET NULL",
        ReferentialAction.SetDefault => "SET DEFAULT",
        _ => throw new ArgumentOutOfRangeException(nameof(action))
    };

    private static string Terminate(string sql) => sql.TrimEnd().EndsWith(';') ? sql.TrimEnd() : sql.TrimEnd() + ";";
}
